# Generated by Django 5.2.17 on 2026-08-11 21:55

import apps.inscricoes.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('valor_desconto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor de desconto')),
                ('limite_usos', models.PositiveIntegerField(verbose_name='Limite de usos')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Cupom',
                'verbose_name_plural': 'Cupons',
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('celular', models.CharField(max_length=20, verbose_name='Celular')),
                ('nome_responsavel', models.CharField(blank=True, max_length=200, verbose_name='Nome do responsável')),
                ('celular_responsavel', models.CharField(blank=True, max_length=20, verbose_name='Celular do responsável')),
                ('preco_final', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço final')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('comprovante_enviado', 'Comprovante enviado'), ('confirmada', 'Confirmada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=20, verbose_name='Status')),
                ('origem', models.CharField(choices=[('formulario', 'Formulário'), ('importacao', 'Importação')], default='formulario', max_length=20, verbose_name='Origem')),
                ('token', models.CharField(default=apps.inscricoes.models.gerar_token, editable=False, max_length=40, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cupom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inscricoes', to='inscricoes.cupom', verbose_name='Cupom')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscricoes', to='lotes.lote', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'ordering': ['-criado_em'],
            },
        ),
    ]
