# Generated by Django 5.2.17 on 2026-08-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='comprovante_path',
            field=models.CharField(blank=True, max_length=255, verbose_name='Caminho do comprovante'),
        ),
    ]
