# Generated by Django 5.2.17 on 2026-08-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0002_inscricao_comprovante_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='motivo_rejeicao',
            field=models.CharField(blank=True, max_length=500, verbose_name='Motivo da rejeição'),
        ),
    ]
