# Generated by Django 5.2.17 on 2026-08-12 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0003_inscricao_motivo_rejeicao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='checkin_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Check-in em'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='checkin_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Check-in por'),
        ),
        migrations.CreateModel(
            name='CheckinAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('aceita', 'Aceita'), ('duplicada', 'Duplicada'), ('bloqueada', 'Bloqueada')], max_length=20, verbose_name='Resultado')),
                ('codigo_tentado', models.CharField(blank=True, max_length=255, verbose_name='Código tentado')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('inscricao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkin_logs', to='inscricoes.inscricao', verbose_name='Inscrição')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de check-in',
                'verbose_name_plural': 'Logs de check-in',
                'ordering': ['-criado_em'],
            },
        ),
    ]
