# Generated by Django 5.2.17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0004_inscricao_checkin_em_inscricao_checkin_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='codigo_checkin',
            field=models.CharField(default='', editable=False, max_length=6, unique=True, verbose_name='Código de check-in'),
            preserve_default=False,
        ),
    ]
